#!/usr/bin/env bash
# build_assets.sh — turn the design_handoff art pack into embeddable 3DS assets.
# Fonts (OFL Space Grotesk + JetBrains Mono) -> .bcfnt; plates + widget atlas -> .t3x.
# Everything lands in data/ as *.bin so the Makefile's bin2s rule embeds it into the ELF
# (works for both .3dsx and .cia; no romfs plumbing). Re-runnable; fonts are cached.
set -euo pipefail
export DEVKITPRO=${DEVKITPRO:-/opt/devkitpro}
export PATH="$DEVKITPRO/tools/bin:$PATH"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ART="$ROOT/design_handoff_3dgba_ui/assets_3ds"
DATA="$ROOT/data"
FCACHE="$ROOT/tools/.fontcache"
THEME="${1:-indigo}"
mkdir -p "$DATA" "$FCACHE"

echo "== fonts =="
fetch() { [ -s "$FCACHE/$2" ] || curl -sL --max-time 40 "$1" -o "$FCACHE/$2"; }
# JetBrains Mono ships static TTFs; Space Grotesk on Google Fonts is a variable font, so
# fetch it once and instance the weights we need with fonttools (both OFL, embeddable).
fetch "https://github.com/JetBrains/JetBrainsMono/raw/master/fonts/ttf/JetBrainsMono-Medium.ttf" jbm-med.ttf
fetch "https://github.com/JetBrains/JetBrainsMono/raw/master/fonts/ttf/JetBrainsMono-Bold.ttf"   jbm-bold.ttf
fetch "https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/spacegrotesk/SpaceGrotesk%5Bwght%5D.ttf" sg-var.ttf
[ -s "$FCACHE/sg-bold.ttf" ] || python3 -m fontTools.varLib.instancer "$FCACHE/sg-var.ttf" wght=700 -o "$FCACHE/sg-bold.ttf" >/dev/null
[ -s "$FCACHE/sg-med.ttf"  ] || python3 -m fontTools.varLib.instancer "$FCACHE/sg-var.ttf" wght=500 -o "$FCACHE/sg-med.ttf"  >/dev/null
bake() { mkbcfnt "$FCACHE/$1" -s "$2" -o "$DATA/fnt_$3.bin"; echo "  fnt_$3 ($2pt)"; }
bake sg-bold.ttf 11 sg_bold      # buttons / titles (~14px native)
bake sg-med.ttf  10 sg_med       # names / body / list (~13px native)
bake jbm-med.ttf  7 jbm_med      # mono labels / codes / hints (~9px native)
bake jbm-bold.ttf 8 jbm_bold     # caps / values (~10px native)

# This tex3ds build only does single-image -> t3x (no atlas / .t3s), so every plate and every
# widget becomes its own tiny compressed t3x. The loader (assets.c) loads each into a 1-image
# spritesheet. A generated header lists the names as X-macros so the loader stays in sync.
GEN="$ROOT/source/assets_gen.h"
{
  echo "// GENERATED by tools/build_assets.sh — do not edit. Plate + widget id lists."
  echo "#pragma once"
  echo "// X(id, sym) : id = C string used at runtime; sym = the embedded _bin symbol stem."
  echo "#define ASSET_PLATES \\"
} > "$GEN"

echo "== plates ($THEME) =="
for png in "$ART/plates/$THEME"/*.png; do
  name="$(basename "$png" .png)"; sym="pl_$(echo "$name" | tr '-' '_')"
  tex3ds -f rgba8 -z auto "$png" -o "$DATA/$sym.bin"
  printf '\tX("%s", %s) \\\n' "$name" "$sym" >> "$GEN"
done
echo >> "$GEN"; echo "#define ASSET_WIDGETS \\" >> "$GEN"
echo "  $(ls "$ART/plates/$THEME"/*.png | wc -l | tr -d ' ') plates"

echo "== widgets ($THEME) =="
for png in "$ART/widgets/$THEME"/*.png; do
  name="$(basename "$png" .png)"; sym="wg_$(echo "$name" | tr '-' '_')"
  tex3ds -f rgba8 -z auto "$png" -o "$DATA/$sym.bin"
  printf '\tX("%s", %s) \\\n' "$name" "$sym" >> "$GEN"
done
echo >> "$GEN"
echo "  $(ls "$ART/widgets/$THEME"/*.png | wc -l | tr -d ' ') widgets -> source/assets_gen.h"

echo "== done =="
ls "$DATA" | wc -l | awk '{printf "  %d files, ", $1}'
du -sh "$DATA" | cut -f1
